const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("Starting deployment on:", hre.network.name);

  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying with account:", deployer.address);

  // 1. Deploy TrustToken
  const TrustToken = await hre.ethers.getContractFactory("TrustToken");
  const trustToken = await TrustToken.deploy();
  await trustToken.waitForDeployment();
  const trustTokenAddr = await trustToken.getAddress();
  console.log("TRUST Token deployed to:", trustTokenAddr);

  // 2. Deploy ReputationNFT
  const ReputationNFT = await hre.ethers.getContractFactory("ReputationNFT");
  const reputationNFT = await ReputationNFT.deploy(deployer.address);
  await reputationNFT.waitForDeployment();
  const reputationNFTAddr = await reputationNFT.getAddress();
  console.log("ReputationNFT deployed to:", reputationNFTAddr);

  // 3. Deploy VouchSystem
  const VouchSystem = await hre.ethers.getContractFactory("VouchSystem");
  const vouchSystem = await VouchSystem.deploy(trustTokenAddr, deployer.address);
  await vouchSystem.waitForDeployment();
  const vouchSystemAddr = await vouchSystem.getAddress();
  console.log("VouchSystem deployed to:", vouchSystemAddr);

  // 4. Deploy LendingPool (linking TrustToken and ReputationNFT)
  const LendingPool = await hre.ethers.getContractFactory("LendingPool");
  const lendingPool = await LendingPool.deploy(trustTokenAddr, reputationNFTAddr);
  await lendingPool.waitForDeployment();
  const lendingPoolAddr = await lendingPool.getAddress();
  console.log("LendingPool deployed to:", lendingPoolAddr);

  // 5. Link ReputationNFT to LendingPool
  console.log("Linking ReputationNFT to LendingPool...");
  await reputationNFT.setLendingPool(lendingPoolAddr);

  // 6. Provide deployer with some tokens (not pool since it's P2P)
  console.log("Transferring 1M TRUST to deployer...");
  // Deployer already gets tokens from constructor of TrustToken usually, 
  // but let's make sure we have plenty.

  // 7. Write contracts.json
  const contractsJson = {
    network: hre.network.name,
    chainId: String(hre.network.config.chainId || 31337),
    deployedAt: new Date().toISOString(),
    StableToken: trustTokenAddr,
    TrustToken: trustTokenAddr,
    LendingPool: lendingPoolAddr,
    ReputationNFT: reputationNFTAddr,
    VouchSystem: vouchSystemAddr,
    _note: "This file is auto-generated by blockchain/scripts/deploy.js. DO NOT EDIT MANUALLY."
  };

  const configJsonPath = path.join(__dirname, "../../src/config/contracts.json");
  fs.writeFileSync(configJsonPath, JSON.stringify(contractsJson, null, 2));

  const libJsonPath = path.join(__dirname, "../../src/lib/contracts.json");
  fs.writeFileSync(libJsonPath, JSON.stringify(contractsJson, null, 2));

  // 8. Auto-export ABIs to frontend
  const contractsDir = path.join(__dirname, "../../src/contracts");
  const abiFiles = ["TrustToken", "LendingPool", "ReputationNFT", "VouchSystem"];

  abiFiles.forEach(name => {
    const artifact = hre.artifacts.readArtifactSync(name);
    fs.writeFileSync(path.join(contractsDir, `${name}.json`), JSON.stringify(artifact, null, 2));
  });
  console.log("✓ ABIs exported to frontend.");

  // ═══════════════════════════════════════════
  // 9. DEMO SETUP — updated for P2P flow
  // ═══════════════════════════════════════════
  console.log("\n🎮 Setting up P2P demo state...");

  const signers = await hre.ethers.getSigners();
  const borrower = signers[1];  
  const lenderAcct = signers[2];   

  // a) Transfer TRUST to lender
  console.log("  → Transferring 10,000 TRUST to lender", lenderAcct.address);
  await trustToken.transfer(lenderAcct.address, hre.ethers.parseUnits("10000", 18));

  // b) Transfer TRUST to borrower
  console.log("  → Transferring 500 TRUST to borrower", borrower.address);
  await trustToken.transfer(borrower.address, hre.ethers.parseUnits("500", 18));

  // c) Initialize borrower identity
  console.log("  → Initializing borrower identity node...");
  await lendingPool.connect(borrower).initializeUser();

  // d) Adjust score for demo
  console.log("  → Setting borrower trust score to 68 (Silver/Gold Gateway)...");
  await lendingPool.updateTrustScore(borrower.address, 68);

  // e) Create a P2P loan request
  console.log("  → Creating 120 TRUST loan request for borrower (Vouch-Backed)...");
  // 0 = VouchBacked, 1 = Collateral, 2 = TrustOnly (cap 10)
  await lendingPool.connect(borrower).submitLoanRequest(hre.ethers.parseUnits("120", 18), 30, 0);

  console.log("──────────────────────────────────────────────────");
  console.log("🎮 P2P DEMO STATE READY");
  console.log("  Borrower:", borrower.address);
  console.log("  Lender Available:", lenderAcct.address);
  console.log("  Current Requests: 1 (120 TRUST)");
  console.log("──────────────────────────────────────────────────");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
